### ISSUE TITLE
Task1

### ISSUE THREAD

**Issue by edukambarov** [GB-GitAdvanced-Trials/GitAdvanced#1]
1. Добавить текстовый файл с непошлым, 

но смешным анекдотом в файл ***anecdote.txt***.

2. Для работы использовать отдельную ветку **1-anecdote**.

Список команд:

```

git clone https://github.com/GB-GitAdvanced-Trials/GitAdvanced.git

git branch 1-anecdote

git switch 1-anecdote

```

Cоздаём в **клонированном на свою машину** репозитории файл ***anecdote.txt*** и помещаем туда анекдот.

```
git add anecdote.txt

git commit -m 'anecdote added'

git push -u origin 1-anecdote

```
C нетерпением жду качественный анекдот!

**Comment by anna-kudrow** [comment]
ready

**Comment by edukambarov** [comment]
everything is ok
